version: '3.2'
services:
  mongo:
    image: mongo
    container_name: 'my-mongo-container'
    volumes:
      - db-data:/data/db
    ports:
      - '27017-27019:27017-27019'
    restart: always

volumes:
  db-data: